original_repo: https://github.com/vlctechhub/freedomsoftwareday

keywords: "diversidad, tecnología, evento, taller, charla, vlctechhub, valencia, conferencia, cfp, técnica, gdcfpd"
title: "Software Freedom Day - 21 de septiembre - VLCTechHub"
description: "VLCTechHub se une a la iniciativa del Software Freedom Day"
ogimage: "https://globaldiversitycfpday.vlctechhub.org/assets/images/vlctechhub_global_diversity_cfp_day.png"

sass:
    sass_dir: assets/_sass
    style: compressed
